name: Sávio Lucena
description: Blogging about stuffs
meta_description: "Your New Jekyll Site, Blogging about stuffs"

aboutPage: true

markdown: redcarpet
highlighter: pygments
gems: [jekyll-paginate]
paginate: 20
baseurl: /
domain_name: 'http://saviolucena.com'
google_analytics: 'UA-72132341-1'
disqus: false
disqus_shortname: 'saviolucena'

# Details for the RSS feed generator
url:            'http://saviolucena.com'
author:         'Sávio Lucena'
# authorTwitter:  'YourTwitterUsername'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
