name: Sávio Lucena
description: Exploring the world of web development
meta_description: 'Exploring the world of web development'

aboutPage: true

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
highlighter: rouge
gems: [jekyll-paginate]
paginate: 20
baseurl: /
domain_name: 'http://saviolucena.com'
google_analytics: 'UA-72132341-1'
disqus: true
disqus_shortname: 'saviolucena'
future: true

# Details for the RSS feed generator
url:            'http://saviolucena.com'
author:         'Sávio Lucena'
# authorTwitter:  'YourTwitterUsername'

email:          'saviogl@gmail.com'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
